project: 'dbc-reproduce'
program: dbc/main_dp.py
method: grid
name: Pick-dp

parameters:
  alg:
    value: dp 
  bc-num-epochs:
    value: 15000  
  depth:
    value: 2 
  hidden-dim:
    value: 1200 
  env-name:
    value: FetchPickAndPlaceDiffHoldout-v0 
  lr:
    value: 1e-5 # 0.000005
  traj-load-path:
    value: expert_datasets/pick.pt
  save-dir:
    value: data/trained_models/dp
  vid-fps:
    value: 100 
  goal-noise-ratio:
    value: 1.25 
  noise-ratio:
    value: 1.25 
  seed:
    values: [1] # [1, 2, 3]  
  # traj-frac:
  #   value: 0.25
  # load-file:
  #   value: data/trained_models/25_7/FetchPickAndPlaceDiffHoldout-v0/debug/model_190000.pt
  # eval-only:
  #   value: True
