project: 'dbc-reproduce'
program: dbc/main.py
method: grid
name: "HalfCheetah-dbc"

parameters:
  alg:
    value: dbc 
  bc-num-epochs:
    value: 1000
  depth:
    value: 2
  hidden-dim:
    value: 256 
  coeff:
    value: 0.2
  cuda:
    value: True 
  ddpm-path:
    value: data/dm/trained_models/halfcheetah_ddpm.pt
  env-name:
    value: HalfCheetah-v3
  lr:
    value: 0.0002
  traj-load-path:
    value: ./expert_datasets/halfcheetah.pt 
  seed:
    values: [1, 2, 3]