project: 'dbc-reproduce'
program: dbc/main.py
method: grid
name: "Hand-bc"

parameters:
  alg:
    value: bc 
  bc-num-epochs:
    value: 5000 
  depth:
    value: 2
  hidden-dim:
    value: 512 
  env-name:
    value: CustomHandManipulateBlockRotateZ-v2
  log-interval:
    value: 1000 
  lr:
    value: 0.0001 
  traj-load-path:
    value: ./expert_datasets/hand.pt 
  vid-fps:
    value: 100 
  seed:
    values: [1,2,3]