project: 'dbc-reproduce'
program: dbc/main.py
method: grid
name: "Hand-dbc"

parameters:
  alg:
    value: dbc 
  bc-num-epochs:
    value: 5000 
  coeff:
    value: 10
  coeff-bc:
    value: 1 
  ddpm-path:
    value: data/dm/trained_models/hand_ddpm.pt 
  depth:
    value: 2
  hidden-dim:
    value: 512 
  env-name:
    value: CustomHandManipulateBlockRotateZ-v2 
  lr:
    value: 0.0001 
  traj-load-path:
    value: ./expert_datasets/hand.pt 
  vid-fps:
    value: 100 
  seed:
    values: [1,2,3]