project: 'dbc-reproduce'
program: dbc/main.py
method: grid
name: "Maze-dbc"

parameters:
  alg:
    value: dbc 
  bc-num-epochs:
    value: 2000
  depth:
    value: 3 
  hidden-dim:
    value: 256
  coeff:
    value: 30 
  coeff-bc:
    value: 1 
  ddpm-path:
    value: data/dm/trained_models/maze_ddpm.pt
  env-name:
    value: maze2d-medium-v2 
  lr:
    value: 0.00005 
  traj-load-path:
    value: ./expert_datasets/maze.pt 
  seed:
    values: [1, 2, 3]